//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColonyConcierge.Mobile.Customer.Localization.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColonyConcierge.Mobile.Customer.Localization.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Account.
        /// </summary>
        public static string AccountCancel {
            get {
                return ResourceManager.GetString("AccountCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel your account? If you are sure click &quot;Yes&quot; below. Otherwise click &quot;No&quot;.
        /// </summary>
        public static string AccountCancelMessage {
            get {
                return ResourceManager.GetString("AccountCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Security.
        /// </summary>
        public static string AccountSecurity {
            get {
                return ResourceManager.GetString("AccountSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item(s).
        /// </summary>
        public static string AddItems {
            get {
                return ResourceManager.GetString("AddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add items to your shopping list.
        /// </summary>
        public static string AddItemShoppingList {
            get {
                return ResourceManager.GetString("AddItemShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment Method.
        /// </summary>
        public static string AddPaymentMethod {
            get {
                return ResourceManager.GetString("AddPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches? Tap here to add your address.
        /// </summary>
        public static string AddressNoMatches {
            get {
                return ResourceManager.GetString("AddressNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your Service Address.
        /// </summary>
        public static string AddServiceAddressTitle {
            get {
                return ResourceManager.GetString("AddServiceAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a member?.
        /// </summary>
        public static string AlreadyMember {
            get {
                return ResourceManager.GetString("AlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an active cart, if you change your current time slot your previous cart will be cleared. To continue click Ok. Otherwise click Cancel..
        /// </summary>
        public static string AnActiveCart {
            get {
                return ResourceManager.GetString("AnActiveCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Time.
        /// </summary>
        public static string AnyTime {
            get {
                return ResourceManager.GetString("AnyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment #.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment/Unit#.
        /// </summary>
        public static string ApartmentUnit {
            get {
                return ResourceManager.GetString("ApartmentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2017 AsystYou.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but our services are not currently available in your area..
        /// </summary>
        public static string AreaInvalid {
            get {
                return ResourceManager.GetString("AreaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the form below to get a coupon when we arrive!.
        /// </summary>
        public static string BeTheFirstKnow {
            get {
                return ResourceManager.GetString("BeTheFirstKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand substitution allows your shopper to purchase a different brand if your preferred brand is not available..
        /// </summary>
        public static string BrandDescription {
            get {
                return ResourceManager.GetString("BrandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string BrandField {
            get {
                return ResourceManager.GetString("BrandField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Substitution.
        /// </summary>
        public static string BrandSubstitution {
            get {
                return ResourceManager.GetString("BrandSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand (32 Character Limit).
        /// </summary>
        public static string BrandTitle {
            get {
                return ResourceManager.GetString("BrandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Address.
        /// </summary>
        public static string BusinessAddress {
            get {
                return ResourceManager.GetString("BusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating.
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this service? If so click &quot;Yes&quot; below. Otherwise, click &quot;No&quot;..
        /// </summary>
        public static string CancelMessage {
            get {
                return ResourceManager.GetString("CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order.
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not found service.
        /// </summary>
        public static string CanNotFoundService {
            get {
                return ResourceManager.GetString("CanNotFoundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use this card!.
        /// </summary>
        public static string CanNotUseThisCard {
            get {
                return ResourceManager.GetString("CanNotUseThisCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Information.
        /// </summary>
        public static string CardInformation {
            get {
                return ResourceManager.GetString("CardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Nickname.
        /// </summary>
        public static string CardNickName {
            get {
                return ResourceManager.GetString("CardNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Services.
        /// </summary>
        public static string CarServices {
            get {
                return ResourceManager.GetString("CarServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The menu is available from {0} to {1}..
        /// </summary>
        public static string CheckMenuAvailableText {
            get {
                return ResourceManager.GetString("CheckMenuAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The menu is not available for your selected time..
        /// </summary>
        public static string CheckMenuAvailableTextNoTime {
            get {
                return ResourceManager.GetString("CheckMenuAvailableTextNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose {0} Optional.
        /// </summary>
        public static string ChooseOptional {
            get {
                return ResourceManager.GetString("ChooseOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose {0} Required.
        /// </summary>
        public static string ChooseRequired {
            get {
                return ResourceManager.GetString("ChooseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CID.
        /// </summary>
        public static string CID {
            get {
                return ResourceManager.GetString("CID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder now. The restaurant is closed at this time..
        /// </summary>
        public static string CloseAtThisTime {
            get {
                return ResourceManager.GetString("CloseAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Contact Information.
        /// </summary>
        public static string ContactInfoTitle {
            get {
                return ResourceManager.GetString("ContactInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Payment.
        /// </summary>
        public static string ContinuetoPayment {
            get {
                return ResourceManager.GetString("ContinuetoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number should be {0} numbers.
        /// </summary>
        public static string CreditCardNumberRequire {
            get {
                return ResourceManager.GetString("CreditCardNumberRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number should be at least {0} numbers.
        /// </summary>
        public static string CreditCardNumberRequireMin {
            get {
                return ResourceManager.GetString("CreditCardNumberRequireMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number should be from {0} to {1} numbers.
        /// </summary>
        public static string CreditCardNumberRequireMinMax {
            get {
                return ResourceManager.GetString("CreditCardNumberRequireMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC2.
        /// </summary>
        public static string CVC2 {
            get {
                return ResourceManager.GetString("CVC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this card?.
        /// </summary>
        public static string DeleteCardMessage {
            get {
                return ResourceManager.GetString("DeleteCardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery To:.
        /// </summary>
        public static string DeliverTo {
            get {
                return ResourceManager.GetString("DeliverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date/Time:.
        /// </summary>
        public static string DeliveryStarts {
            get {
                return ResourceManager.GetString("DeliveryStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date/Time.
        /// </summary>
        public static string DeliveryWindow {
            get {
                return ResourceManager.GetString("DeliveryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery time is our best estimate when your order will arrive. We can not guarantee delivery will take place during this time..
        /// </summary>
        public static string DeliveryWindowMessage {
            get {
                return ResourceManager.GetString("DeliveryWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner Menu.
        /// </summary>
        public static string DinnerMenu {
            get {
                return ResourceManager.GetString("DinnerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code.
        /// </summary>
        public static string DiscountCode {
            get {
                return ResourceManager.GetString("DiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string DoNotAccount {
            get {
                return ResourceManager.GetString("DoNotAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Cleaning.
        /// </summary>
        public static string DryCleaning {
            get {
                return ResourceManager.GetString("DryCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Order.
        /// </summary>
        public static string EditOrder {
            get {
                return ResourceManager.GetString("EditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailInput {
            get {
                return ResourceManager.GetString("EmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already taken.
        /// </summary>
        public static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Username.
        /// </summary>
        public static string EmailUsername {
            get {
                return ResourceManager.GetString("EmailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Discount Code.
        /// </summary>
        public static string EnterDiscountCode {
            get {
                return ResourceManager.GetString("EnterDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errands.
        /// </summary>
        public static string Errands {
            get {
                return ResourceManager.GetString("Errands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errand To Perform.
        /// </summary>
        public static string ErrandToPerform {
            get {
                return ResourceManager.GetString("ErrandToPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date is invalid.
        /// </summary>
        public static string ExpirationDateIsExpired {
            get {
                return ResourceManager.GetString("ExpirationDateIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date is not in correct format - MM/YYYY.
        /// </summary>
        public static string ExpirationDateNotCorrect {
            get {
                return ResourceManager.GetString("ExpirationDateNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQPageTitle {
            get {
                return ResourceManager.GetString("FAQPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus Fee/Taxes.
        /// </summary>
        public static string FeeTaxes {
            get {
                return ResourceManager.GetString("FeeTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From my saved lists.
        /// </summary>
        public static string FromMySavedLists {
            get {
                return ResourceManager.GetString("FromMySavedLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic brands will only be purchased if you authorize them..
        /// </summary>
        public static string GenericDescription {
            get {
                return ResourceManager.GetString("GenericDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Substitution.
        /// </summary>
        public static string GenericSubstitution {
            get {
                return ResourceManager.GetString("GenericSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET STARTED.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us find you.
        /// </summary>
        public static string HelpUsToFindYou {
            get {
                return ResourceManager.GetString("HelpUsToFindYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Number.
        /// </summary>
        public static string HomeNumber {
            get {
                return ResourceManager.GetString("HomeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string Howitworks {
            get {
                return ResourceManager.GetString("Howitworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am here.
        /// </summary>
        public static string Iamhere {
            get {
                return ResourceManager.GetString("Iamhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete or invalid address provided.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Format.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 10 characters, one uppercase, one number or one special character..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Preferred.
        /// </summary>
        public static string IsPreferred {
            get {
                return ResourceManager.GetString("IsPreferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEM.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Preferences.
        /// </summary>
        public static string ItemPreferancesTitle {
            get {
                return ResourceManager.GetString("ItemPreferancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEMS.
        /// </summary>
        public static string ItemsUp {
            get {
                return ResourceManager.GetString("ItemsUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larger.
        /// </summary>
        public static string Larger {
            get {
                return ResourceManager.GetString("Larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larger Items.
        /// </summary>
        public static string LargerItems {
            get {
                return ResourceManager.GetString("LargerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information has been received. We will notify you as soon as AsystYou is available in your area..
        /// </summary>
        public static string LeadsGenerationMessage {
            get {
                return ResourceManager.GetString("LeadsGenerationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us take care of that for you..
        /// </summary>
        public static string LetUsTakeCare {
            get {
                return ResourceManager.GetString("LetUsTakeCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Services are Off.
        /// </summary>
        public static string LocationServicesOff {
            get {
                return ResourceManager.GetString("LocationServicesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Successful.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch Menu.
        /// </summary>
        public static string LunchMenu {
            get {
                return ResourceManager.GetString("LunchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is closed.
        /// </summary>
        public static string MenuIsClosed {
            get {
                return ResourceManager.GetString("MenuIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage Fee.
        /// </summary>
        public static string MileageFee {
            get {
                return ResourceManager.GetString("MileageFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be at least {1} characters long..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/YY.
        /// </summary>
        public static string MMYY {
            get {
                return ResourceManager.GetString("MMYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/YYYY.
        /// </summary>
        public static string MMYYYY {
            get {
                return ResourceManager.GetString("MMYYYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile:.
        /// </summary>
        public static string MobileInput {
            get {
                return ResourceManager.GetString("MobileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cart.
        /// </summary>
        public static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not determine your current address, please enter it manually..
        /// </summary>
        public static string MyLocationInvaild {
            get {
                return ResourceManager.GetString("MyLocationInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string MyOrder {
            get {
                return ResourceManager.GetString("MyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string MyPaymentMethod {
            get {
                return ResourceManager.GetString("MyPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Request.
        /// </summary>
        public static string MyRequest {
            get {
                return ResourceManager.GetString("MyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shopping List(s).
        /// </summary>
        public static string MyShoppingList {
            get {
                return ResourceManager.GetString("MyShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your universal preferences below:.
        /// </summary>
        public static string MYShoppingPref {
            get {
                return ResourceManager.GetString("MYShoppingPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successful.
        /// </summary>
        public static string MYShoppingPrefMessage {
            get {
                return ResourceManager.GetString("MYShoppingPrefMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Business.
        /// </summary>
        public static string NameOfBusiness {
            get {
                return ResourceManager.GetString("NameOfBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special request? Tell us here....
        /// </summary>
        public static string NeedSpecialWithYourMeal {
            get {
                return ResourceManager.GetString("NeedSpecialWithYourMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Delivery.
        /// </summary>
        public static string NextDelivery {
            get {
                return ResourceManager.GetString("NextDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Pickup.
        /// </summary>
        public static string NextPickup {
            get {
                return ResourceManager.GetString("NextPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more deliveries today.
        /// </summary>
        public static string NoMoreDeliveriesToday {
            get {
                return ResourceManager.GetString("NoMoreDeliveriesToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more pickups today.
        /// </summary>
        public static string NoMorePickupToday {
            get {
                return ResourceManager.GetString("NoMorePickupToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Payment Methods.
        /// </summary>
        public static string NoPaymentMethods {
            get {
                return ResourceManager.GetString("NoPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Preference.
        /// </summary>
        public static string NoPreference {
            get {
                return ResourceManager.GetString("NoPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved shopping lists..
        /// </summary>
        public static string NoSavedShoppingCarts {
            get {
                return ResourceManager.GetString("NoSavedShoppingCarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me.
        /// </summary>
        public static string NotifyMe {
            get {
                return ResourceManager.GetString("NotifyMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is expired!.
        /// </summary>
        public static string OrderExpired {
            get {
                return ResourceManager.GetString("OrderExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service History.
        /// </summary>
        public static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other - Errand.
        /// </summary>
        public static string OtherErrand {
            get {
                return ResourceManager.GetString("OtherErrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords Do Not Match.
        /// </summary>
        public static string PasswordMatchError {
            get {
                return ResourceManager.GetString("PasswordMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment Method.
        /// </summary>
        public static string PaymentMethodTitle {
            get {
                return ResourceManager.GetString("PaymentMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string PaymentPageTitle {
            get {
                return ResourceManager.GetString("PaymentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PaymentTitle {
            get {
                return ResourceManager.GetString("PaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Service.
        /// </summary>
        public static string PersonalService {
            get {
                return ResourceManager.GetString("PersonalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Services.
        /// </summary>
        public static string PetServices {
            get {
                return ResourceManager.GetString("PetServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup.
        /// </summary>
        public static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Address.
        /// </summary>
        public static string PickupAddress {
            get {
                return ResourceManager.GetString("PickupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup At:.
        /// </summary>
        public static string PickupAt {
            get {
                return ResourceManager.GetString("PickupAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Only.
        /// </summary>
        public static string PickupOnly {
            get {
                return ResourceManager.GetString("PickupOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Only - Your address is outside this Restaurant&apos;s delivery zone..
        /// </summary>
        public static string PickupOnlyMessage {
            get {
                return ResourceManager.GetString("PickupOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Time:.
        /// </summary>
        public static string PickupTime {
            get {
                return ResourceManager.GetString("PickupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placing Order....
        /// </summary>
        public static string PlacingOrder {
            get {
                return ResourceManager.GetString("PlacingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please hurry up! this menu is closing in .
        /// </summary>
        public static string PleaseHurryUp {
            get {
                return ResourceManager.GetString("PleaseHurryUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select card.
        /// </summary>
        public static string PleaseSelectCard {
            get {
                return ResourceManager.GetString("PleaseSelectCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select {0} time to order.
        /// </summary>
        public static string PleaseSelectTime {
            get {
                return ResourceManager.GetString("PleaseSelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Signing Up you agree to our {0}.
        /// </summary>
        public static string PolicySignupMessage {
            get {
                return ResourceManager.GetString("PolicySignupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions and Privacy Policy.
        /// </summary>
        public static string PolicyTermsConditions {
            get {
                return ResourceManager.GetString("PolicyTermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev.asystyou.com/Privacy/Index#/Privacy.
        /// </summary>
        public static string PolicyUrl {
            get {
                return ResourceManager.GetString("PolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred.
        /// </summary>
        public static string Preferred {
            get {
                return ResourceManager.GetString("Preferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder Now. Next Delivery time is.
        /// </summary>
        public static string PreorderOnlyDeliveryMessage {
            get {
                return ResourceManager.GetString("PreorderOnlyDeliveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder now. Next Pickup time is.
        /// </summary>
        public static string PreorderOnlyPickupMessage {
            get {
                return ResourceManager.GetString("PreorderOnlyPickupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments (64 Character Limit).
        /// </summary>
        public static string ProductComments {
            get {
                return ResourceManager.GetString("ProductComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductNameField {
            get {
                return ResourceManager.GetString("ProductNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name (32 Character Limit).
        /// </summary>
        public static string ProductNameTitle {
            get {
                return ResourceManager.GetString("ProductNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Size/Weight (32 Character Limit).
        /// </summary>
        public static string ProductSizeWeightTitle {
            get {
                return ResourceManager.GetString("ProductSizeWeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide comments here....
        /// </summary>
        public static string ProvideComment {
            get {
                return ResourceManager.GetString("ProvideComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide comments here....
        /// </summary>
        public static string ProvideOrderComment {
            get {
                return ResourceManager.GetString("ProvideOrderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection or failed to connect to server!.
        /// </summary>
        public static string PullDataFailMessage {
            get {
                return ResourceManager.GetString("PullDataFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuanlityField {
            get {
                return ResourceManager.GetString("QuanlityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVE.
        /// </summary>
        public static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the ease and satisfaction of having one less task to do!.
        /// </summary>
        public static string ReceiveDescription {
            get {
                return ResourceManager.GetString("ReceiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Notifications.
        /// </summary>
        public static string ReceiveNotification {
            get {
                return ResourceManager.GetString("ReceiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register notification fail.
        /// </summary>
        public static string RegisterNotificationFail {
            get {
                return ResourceManager.GetString("RegisterNotificationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELAX.
        /// </summary>
        public static string Relax {
            get {
                return ResourceManager.GetString("Relax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this time to do what&apos;s important to you - whether that&apos;s taking a break or catching up..
        /// </summary>
        public static string RelaxDescription {
            get {
                return ResourceManager.GetString("RelaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat this service weekly.
        /// </summary>
        public static string RepeatServiceWeekly {
            get {
                return ResourceManager.GetString("RepeatServiceWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From grocery shopping to house cleaning, we&apos;re here for you..
        /// </summary>
        public static string RequestDescription {
            get {
                return ResourceManager.GetString("RequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required field.
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not available in {1} area..
        /// </summary>
        public static string RestaurantAvailableMessage {
            get {
                return ResourceManager.GetString("RestaurantAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Delivery.
        /// </summary>
        public static string RestaurantDelivery {
            get {
                return ResourceManager.GetString("RestaurantDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant is Closed.
        /// </summary>
        public static string RestaurantIsClosed {
            get {
                return ResourceManager.GetString("RestaurantIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Pickup.
        /// </summary>
        public static string RestaurantPickup {
            get {
                return ResourceManager.GetString("RestaurantPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants near you.
        /// </summary>
        public static string RestaurantsNearYou {
            get {
                return ResourceManager.GetString("RestaurantsNearYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        public static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save shopping list.
        /// </summary>
        public static string SaveShoppingList {
            get {
                return ResourceManager.GetString("SaveShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Date.
        /// </summary>
        public static string ScheduledDate {
            get {
                return ResourceManager.GetString("ScheduledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled For.
        /// </summary>
        public static string ScheduledFor {
            get {
                return ResourceManager.GetString("ScheduledFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Time.
        /// </summary>
        public static string ScheduledTime {
            get {
                return ResourceManager.GetString("ScheduledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule your shopping service today..
        /// </summary>
        public static string ScheduleYourShopping {
            get {
                return ResourceManager.GetString("ScheduleYourShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know when, where and what you need and we’ll take care of it for you!.
        /// </summary>
        public static string ScheduleYourShoppingMessage {
            get {
                return ResourceManager.GetString("ScheduleYourShoppingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Lunch.
        /// </summary>
        public static string SchoolLunch {
            get {
                return ResourceManager.GetString("SchoolLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer.
        /// </summary>
        public static string SecurityAnswer {
            get {
                return ResourceManager.GetString("SecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        public static string SecurityQuestion {
            get {
                return ResourceManager.GetString("SecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address.
        /// </summary>
        public static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update unsuccessful, please try again..
        /// </summary>
        public static string ServiceAddressError {
            get {
                return ResourceManager.GetString("ServiceAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successful.
        /// </summary>
        public static string ServiceAddressSuccess {
            get {
                return ResourceManager.GetString("ServiceAddressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address.
        /// </summary>
        public static string ServiceAddressTitle {
            get {
                return ResourceManager.GetString("ServiceAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Date.
        /// </summary>
        public static string ServiceDate {
            get {
                return ResourceManager.GetString("ServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Fee.
        /// </summary>
        public static string ServiceFee {
            get {
                return ResourceManager.GetString("ServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Listing.
        /// </summary>
        public static string ServiceListing {
            get {
                return ResourceManager.GetString("ServiceListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Descriptions.
        /// </summary>
        public static string ServicesAndFeesPageTitle {
            get {
                return ResourceManager.GetString("ServicesAndFeesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but our services are not currently available in your area..
        /// </summary>
        public static string ServicesAreNotCurrentlyAvailable {
            get {
                return ResourceManager.GetString("ServicesAreNotCurrentlyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but our services are not currently available in.
        /// </summary>
        public static string ServicesAreNotCurrentlyAvailableZipCode {
            get {
                return ResourceManager.GetString("ServicesAreNotCurrentlyAvailableZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From grocery shopping to house cleaning, we&apos;re here for you.
        /// </summary>
        public static string ServiceTypeDescription {
            get {
                return ResourceManager.GetString("ServiceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same day shopping must be scheduled before 6 pm. If this is an emergency you can try to contact us by phone or email..
        /// </summary>
        public static string ShoppingErrorDateMessage {
            get {
                return ResourceManager.GetString("ShoppingErrorDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping List.
        /// </summary>
        public static string ShoppingList {
            get {
                return ResourceManager.GetString("ShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list name.
        /// </summary>
        public static string ShoppingListName {
            get {
                return ResourceManager.GetString("ShoppingListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Preferences.
        /// </summary>
        public static string ShoppingPreferances {
            get {
                return ResourceManager.GetString("ShoppingPreferances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shopping Preferences.
        /// </summary>
        public static string ShoppingTitle {
            get {
                return ResourceManager.GetString("ShoppingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in/Sign up.
        /// </summary>
        public static string SigninSignup {
            get {
                return ResourceManager.GetString("SigninSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string SignUpUp {
            get {
                return ResourceManager.GetString("SignUpUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the size/weight for your item is not available, your shopper can purchase a different size..
        /// </summary>
        public static string SizeDescription {
            get {
                return ResourceManager.GetString("SizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size/Weight.
        /// </summary>
        public static string SizeWeightField {
            get {
                return ResourceManager.GetString("SizeWeightField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size/Weight - .
        /// </summary>
        public static string SizeWeightLess {
            get {
                return ResourceManager.GetString("SizeWeightLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size/Weight Substitution.
        /// </summary>
        public static string SizeWeightSubstitution {
            get {
                return ResourceManager.GetString("SizeWeightSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller.
        /// </summary>
        public static string Smaller {
            get {
                return ResourceManager.GetString("Smaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller Items.
        /// </summary>
        public static string SmallerItems {
            get {
                return ResourceManager.GetString("SmallerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, we are working hard to fix it. please try again later..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions.
        /// </summary>
        public static string SpecialInstructions {
            get {
                return ResourceManager.GetString("SpecialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions.
        /// </summary>
        public static string SpecialInstructionsProvide {
            get {
                return ResourceManager.GetString("SpecialInstructionsProvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special request.
        /// </summary>
        public static string SpecialRequest {
            get {
                return ResourceManager.GetString("SpecialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Preferences.
        /// </summary>
        public static string StorePreferances {
            get {
                return ResourceManager.GetString("StorePreferances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update unsuccessful, please try again..
        /// </summary>
        public static string SubscriptionUpdateError {
            get {
                return ResourceManager.GetString("SubscriptionUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successful.
        /// </summary>
        public static string SubscriptionUpdateSuccess {
            get {
                return ResourceManager.GetString("SubscriptionUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Subscription.
        /// </summary>
        public static string SubscriptionUpdateTitle {
            get {
                return ResourceManager.GetString("SubscriptionUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SupportPageTitle {
            get {
                return ResourceManager.GetString("SupportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sushi Menu.
        /// </summary>
        public static string SushiMenu {
            get {
                return ResourceManager.GetString("SushiMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking care of the home front..
        /// </summary>
        public static string TakingCare {
            get {
                return ResourceManager.GetString("TakingCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time must be before End Time.
        /// </summary>
        public static string TheDateAreIncorrect {
            get {
                return ResourceManager.GetString("TheDateAreIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time changed to.
        /// </summary>
        public static string TimeChanged {
            get {
                return ResourceManager.GetString("TimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRY AGAIN.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To retrieve your current location, you must enable Location Services in your settings..
        /// </summary>
        public static string TurnOnLocationMessage {
            get {
                return ResourceManager.GetString("TurnOnLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit#.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update was unsuccessful, please try again..
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successful.
        /// </summary>
        public static string UpdateInformation {
            get {
                return ResourceManager.GetString("UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Subscription.
        /// </summary>
        public static string UpdateSubscription {
            get {
                return ResourceManager.GetString("UpdateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use My Current Location.
        /// </summary>
        public static string UseCurrentLocation {
            get {
                return ResourceManager.GetString("UseCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        public static string ViewCart {
            get {
                return ResourceManager.GetString("ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsystYou.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatever your errand is we can take it off your plate..
        /// </summary>
        public static string WhateverYourErrand {
            get {
                return ResourceManager.GetString("WhateverYourErrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Number.
        /// </summary>
        public static string WorkNumber {
            get {
                return ResourceManager.GetString("WorkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty..
        /// </summary>
        public static string YourCartIsEmpty {
            get {
                return ResourceManager.GetString("YourCartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order was placed successfully..
        /// </summary>
        public static string YourOrderSuccessfully {
            get {
                return ResourceManager.GetString("YourOrderSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order was placed successfully..
        /// </summary>
        public static string YourOrderWasPlaced {
            get {
                return ResourceManager.GetString("YourOrderWasPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but our services are not currently available in {0}..
        /// </summary>
        public static string ZipInvalid {
            get {
                return ResourceManager.GetString("ZipInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have Asystants available in your area..
        /// </summary>
        public static string ZipValid {
            get {
                return ResourceManager.GetString("ZipValid", resourceCulture);
            }
        }
    }
}
