using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ColonyConcierge.APIData.Data
{
    /// <summary>
    /// A value that represents the conditions under which a service may be considered mutable.
    /// </summary>
    //public enum ScheduledServiceMutability
    //{
    //    /// <summary>
    //    /// The service cannot be changed
    //    /// </summary>
    //    ReadOnly,
    //    /// <summary>
    //    /// The service an only be changed if it is being promoted to an emergency
    //    /// </summary>
    //    IfEmergency,
    //    /// <summary>
    //    /// The service may be freely edited
    //    /// </summary>
    //    Editable
    //}

    public class ScheduledServiceMutability
    {
        /// <summary>
        /// A value that represents the conditions under which a service may be considered mutable.
        /// </summary>
        public enum MutabilityStatuses
        {
            /// <summary>
            /// The service cannot be changed
            /// </summary>
            ReadOnly,
            /// <summary>
            /// The service an only be changed if it is being promoted to an emergency
            /// </summary>
            IfEmergency,
            /// <summary>
            /// The service may be freely edited
            /// </summary>
            Editable
        }
        /// <summary>
        /// The ID of the scheduled service that this object describes
        /// </summary>
        public int ServiceID { get; set; }

        /// <summary>
        /// The mutability state of the scheduled service
        /// </summary>
        public MutabilityStatuses Mutability { get; set; }

        /// <summary>
        /// A summary generated by the server for why the service may not be editable
        /// </summary>
        public string Reason { get; set; }
    }

    


}
